all: thread_ex input_ex

thread_ex: thread_ex.cpp
	g++ -Wall -pthread thread_ex.cpp -o thread_ex

input_ex: input_ex.cpp
	g++ -Wall -pthread input_ex.cpp -o input_ex

clean:
	rm -f thread_ex input_ex


